# Generated by Django 5.1.7 on 2025-03-24 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_example'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'ordering': ('status', '-description'), 'verbose_name': 'Exemplo', 'verbose_name_plural': 'Exemplos'},
        ),
    ]
