# Generated by Django 5.2 on 2025-04-08 01:01

import django.core.validators
import my_app.validators.cod
import my_app.validators.funcoes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_example_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='cod',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), my_app.validators.cod.CodValidator('444444444'), my_app.validators.funcoes.validate_par]),
        ),
    ]
