# Generated by Django 5.2 on 2025-04-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_example_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='nome',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
