# Generated by Django 5.1.7 on 2025-03-25 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Escreva aqui o nome da pessoa.', max_length=100, verbose_name='Nome:')),
                ('birth_date', models.DateField(help_text='Escreva aqui a data de nascimento.', verbose_name='Data de Nascimento:')),
                ('cpf', models.CharField(help_text='Escreva aqui o CPF.', max_length=11, verbose_name='CPF:')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('number', models.CharField(help_text='Escreva aqui o numero do passaporte', max_length=20, verbose_name='Numero:')),
                ('issue_date', models.DateField(help_text='Escreva aqui a data do passaporte', verbose_name='Issue date:')),
                ('expiration_date', models.DateField(help_text='Escreva aqui a data de expiração passaporte', verbose_name='Expiration date:')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aula.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
