# Generated by Django 5.1.7 on 2025-03-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_reporter_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Escreva aqui o nome da Maagazine.', max_length=100, verbose_name='Nome:')),
                ('edition', models.IntegerField(help_text='Escreva aqui o número da edição', verbose_name='Edição:')),
                ('article', models.ManyToManyField(to='aula.article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
