# Generated by Django 5.2 on 2025-04-07 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0003_magazine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aula.reporter'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('obs', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aula.article')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aula.person')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aula.magazine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='magazines',
            field=models.ManyToManyField(blank=True, null=True, through='aula.Publication', through_fields=('article', 'magazine'), to='aula.magazine'),
        ),
    ]
